#!/usr/bin/env bash

[[ -f ~/.rr-launcher ]] && source ~/.rr-launcher

if [ -z ${APPS+x} ]; then
	APPS=('retroarch' 'retroarch32')
fi

i=0

while [ 1 ]
do
	nice -20 ${APPS[$((i++ % ${#APPS[@]}))]}
done

