#!/bin/bash

ACTION=$1
shift

do_help() {
    echo "${1} scanlist" >&2
    echo "${1} list" >&2
}

do_list() {
    nmcli -f SSID dev wifi | awk '{$1=$1;print}' | tail -n +2
}

do_scanlist() {
    do_list
}

do_enable() {
    SSID=$1
    PSK=$2

    nmcli radio wifi on
    nmcli dev wifi connect "$SSID" password "$PSK"
    return 0
}

do_disable() {
    nmcli radio wifi off
}

do_start() {
    nmcli radio wifi on
}

case "${ACTION}" in
    "list")
	do_list
	;;
    "scanlist")
	do_scanlist
	;;
    "start")
	do_start
	;;
    "enable")
	SSID=$1
	PSK=$2
	do_enable "${SSID}" "${PSK}" || exit 1
	;;
    "disable")
	do_disable || exit 1
	;;
    *)
	do_help "${0}"
esac
exit 0
